### ISSUE TITLE
Upload video to existing JobRequest

### ISSUE THREAD

**Issue by yankedev** [exteso/bruno#1]
Customers that created a JobRequest need to be able to attach a video to the case that could help ServiceProvider to estimate the price of the work

**Comment by syjer** [comment]
TODO:
- [x] upload to "s3" the file
- [x] ui for display images/video in job request view
- [x] job for removing unused files
- [x] ui for removing images/videos in job request view
- [x] ui for adding images/videos in job request view

**Comment by syjer** [comment]
done.
