### ISSUE TITLE
ServiceProvider request form

### ISSUE THREAD

**Issue by yankedev** [exteso/bruno#12]
When a user wants to register as a ServiceProvider he should fullfill a form with the following fields:

Company name: Freetext
Field of work: ENUM, multiple selection is possible
Address: autocompletion but don't validate, mandatory
Telephone: Any phone, optional
Contact Email: any email, optional
Numero registro IVA: validate with regex, optional if empty
Note: Freetext

**Comment by yankedev** [comment]
Issue #3 is a pre-requisite for this task. 
Then the ENUM of the "Field of work" field needs to show all those values defined in issue #3

**Comment by syjer** [comment]
TODO:
- [x] update html form
- [x] update sql schema + query
- [x] modify controller for saving request
- [x] update service provider visualization in admin
- [x] update service provider visualization for normal user
- [x] update filtering logic for service requests

**Comment by syjer** [comment]
note: the address autocomplete will be done after.

**Comment by syjer** [comment]
can be considered done.
