### ISSUE TITLE
Describe ServiceWorker competences

### ISSUE THREAD

**Issue by yankedev** [exteso/bruno#3]
Each ServiceWorker may have multiple competences, but to allow a Customer to select who he needs (if he is able to know that) and to simplify the matching algorithm (which ServiceWorker are good candidates for this work?) we group competences using the following definitions:

(currently in italian, we need to translate in english) 
- Impresa costruzioni: fognatura esterna intasata;
- Falegname: scasso porta, rottura serramento;
- Ditta di Impermeabilizzazione: infiltrazione acqua tetto, infiltrazione acqua autorimessa o facciata esterna;
- Idraulico: rottura tubo interno, acqua calda che non arriva, serpentine/riscaldamento non funzionanti;
- Elettricista: luci giardino non funzionanti, presa camera non funzionante, interruttore cantina bloccato;

**Comment by yankedev** [comment]
When a ServiceWorker registers to the application he should select which competences he has.
When a Customer create a new JobRequest he might select the competences required to fix it.

**Comment by DeborahSormani** [comment]
Perfect, I think that for a customer, we have to think a solution for guarantee the high competence of the ServiceProvider in that field.

**Comment by syjer** [comment]
The enums have been defined, the integration work is done in #12
