### ISSUE TITLE
User Registration

### ISSUE THREAD

**Issue by yankedev** [exteso/bruno#4]
Users needs to be able to register to Bruno using their Google/Facebook/Twitter (called IdentityProviders) accounts
Once a user approves the consent screen he can use the application as Customer.

~~There is a button Register on the main page when the user is not logged in
There is also a Login button that force to use an already registered user (in order to avoid creating a new identity using a different IdentityProvider)~~

After a user is registered as a Customer he will be able to ask to become a ServiceProvider (see issue #5)

**Comment by syjer** [comment]
TODO:
- [x] google login
- [x] fb login 
- [x] copy in user table "firstname/lastname" or "username" and email on first login

**Comment by syjer** [comment]
Can be considered done.
