### ISSUE TITLE
Register as ServiceProvider

### ISSUE THREAD

**Issue by yankedev** [exteso/bruno#5]
In the header of a logged-in user there is a "Register as a ServiceProvider" button that start a manual approval flow, composed of 3 steps:
1. User fill-in a form with all the ServiceProvider fields --> Activation is in state PENDING
2. Bruno Administrators can see a list of PENDING/IN_PROGRESS Activations
3. Choose the ServiceProvider profile and generate the correlated payment (Activation Status IN_PROGRESS)
4. Once the user pays the Admin can change Activation to ACTIVE

From the next login, the user will get the role SERVICE_PROVIDER too

**Comment by syjer** [comment]
note:
- when creating the users, we need to have some admins. In the application.yaml register a list of users, that when created are matched against this list and given the appropriate ADMIN type

**Comment by syjer** [comment]
TODO:
- [x] update the top right menu: if normal user: {Home, Register as a ServiceProvider, Logout}, if service provider {Home, My intervention requests, Logout}, if admin: {Home, My intervention requests, Logout}
- [x] on login, in function of user type, redirect to correct home page
- [x] create "Register as a Service Provider" page + api
- [x] add "admin by default" list configuration
- [x] create page for admin

**Comment by DeborahSormani** [comment]
I didn't understand completely the suggestion of syjer.
During the first registration and activation, I think we should create a "sort" of PageProfile of the ServiceProvider, in order that the customer, when receive the offer, can give a first check of the type of the ServiceProvider, as first impression.

**Comment by yankedev** [comment]
In UserProfile page the user cannot assign the admin role himself :-)
Administrators are defined in a config file on the server. When a user log-in we check if userId is in the config property. If yes, user becomes admin

**Comment by syjer** [comment]
The flow is now complete, some usability improvement will be done (tracked in a new task)
